import { SxProps, Theme } from "@mui/material";

export const footerSectionStyles: Record<string, SxProps<Theme>> = {
  container: {
    width: "100%",
    maxWidth: 1400,
    bgcolor: "white",
    pt: { xs: 4, sm: 6, md: 8 },
    pb: { xs: 2, md: 4 },
    margin: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    px: { xs: 2, sm: 4, md: 6 }, // padding for smaller screens
  },
  columns: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: { xs: "1fr", sm: "1fr 1fr", md: "repeat(4, 1fr)" },
    gap: { xs: 3, sm: 4, md: 8 },
    mb: { xs: 4, sm: 6, md: 8 },
  },
  column: {
    pl: 0,
    pr: 0,
  },
  heading: {
    fontWeight: 700,
    fontSize: { xs: "1rem", sm: "1.2rem", md: "1.4rem" },
    mb: 2,
    color: "black",
    fontFamily:
      "'Plus Jakarta Sans', 'Inter', 'Arial', 'Helvetica Neue', sans-serif",
    textAlign: "left",
  },
  link: {
    fontWeight: 400,
    fontSize: { xs: "0.95rem", sm: "1rem", md: "1.2rem" },
    color: "#111",
    fontFamily:
      "'Plus Jakarta Sans', 'Inter', 'Arial', 'Helvetica Neue', sans-serif",
    mb: 1.2,
    textDecoration: "none",
    display: "block",
    cursor: "pointer",
    transition: "color 0.2s",
    textAlign: "left",
    "&:hover": {
      color: "#888",
    },
  },
  subscribeRow: {
    width: "100%",
    display: "flex",
    justifyContent: { xs: "center", sm: "flex-start" },
    alignItems: "center",
    mb: { xs: 3, sm: 4, md: 6 },
  },
  subscribeButton: {
    display: "flex",
    alignItems: "center",
    border: "2px solid #111",
    borderRadius: 999,
    color: "black",
    px: { xs: 2, sm: 3, md: 4 },
    py: { xs: 1, sm: 1.2, md: 1.5 },
    fontSize: { xs: "0.95rem", sm: "1.1rem", md: "1.4rem" },
    fontWeight: 400,
    fontFamily:
      "'Plus Jakarta Sans', 'Inter', 'Arial', 'Helvetica Neue', sans-serif",
    background: "#fff",
    cursor: "pointer",
    minWidth: { xs: "auto", sm: 280, md: 340 },
    justifyContent: "space-between",
    width: "auto",
    boxShadow: 1,
    transition: "background 0.3s, color 0.3s",
    "&:hover": {
      background: "#111",
      color: "#fff",
      "& .subscribe-circle": {
        background: "#fff",
      },
    },
  },
  subscribeCircle: {
    width: { xs: 20, sm: 35, md: 40 },
    height: { xs: 20, sm: 35, md: 40 },
    borderRadius: "50%",
    bgcolor: "#111",
    ml: 2,
    display: "inline-block",
    transition: "background 0.3s",
  },
  copyright: {
    width: "100%",
    textAlign: { xs: "center", md: "right" },
    fontSize: { xs: "0.85rem", sm: "1rem", md: "1.2rem" },
    letterSpacing: "-0.5px",
    color: "#111",
    fontFamily: "'Aeonik Pro', sans-serif",
    mt: 2,
    mb: 1,
  },
};
