import { SxProps, Theme } from "@mui/material";

export const footerSectionStyles: Record<string, SxProps<Theme>> = {
  container: {
    width: "100vw",
    bgcolor: "white",
    borderTop: "2px solid #111",
    pt: { xs: 6, md: 8 },
    pb: { xs: 2, md: 4 },
    px: { xs: 2, md: 8 },
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  columns: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: { xs: "1fr", sm: "1fr 1fr", md: "repeat(4, 1fr)" },
    gap: { xs: 4, md: 8 },
    mb: { xs: 6, md: 8 },
    maxWidth: 1400,
  },
  heading: {
    fontWeight: 700,
    fontSize: { xs: "1.2rem", md: "1.4rem" },
    mb: 2,
    fontFamily: "'Plus Jakarta Sans', 'Inter', 'Arial', 'Helvetica Neue', sans-serif",
  },
  link: {
    fontWeight: 400,
    fontSize: { xs: "1.1rem", md: "1.3rem" },
    color: "#111",
    fontFamily: "'Plus Jakarta Sans', 'Inter', 'Arial', 'Helvetica Neue', sans-serif",
    mb: 1.2,
    textDecoration: "none",
    display: "block",
    cursor: "pointer",
    transition: "color 0.2s",
    '&:hover': {
      color: "#888",
    },
  },
  subscribeRow: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    mb: { xs: 4, md: 6 },
  },
  subscribeButton: {
    display: "flex",
    alignItems: "center",
    border: "2px solid #111",
    borderRadius: 999,
    px: 4,
    py: 1.5,
    fontSize: { xs: "1.1rem", md: "1.4rem" },
    fontWeight: 400,
    fontFamily: "'Plus Jakarta Sans', 'Inter', 'Arial', 'Helvetica Neue', sans-serif",
    background: "#fff",
    cursor: "pointer",
    minWidth: 340,
    justifyContent: "space-between",
    width: { xs: "100%", md: 500 },
    boxShadow: 1,
  },
  subscribeCircle: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    bgcolor: "#111",
    ml: 2,
    display: "inline-block",
  },
  copyright: {
    width: "100%",
    textAlign: "right",
    fontSize: { xs: "1rem", md: "1.2rem" },
    color: "#111",
    fontFamily: "'Plus Jakarta Sans', 'Inter', 'Arial', 'Helvetica Neue', sans-serif",
    mt: 2,
    mb: 1,
    pr: { xs: 0, md: 2 },
  },
}; 